server:
  port: 8080
spring:
  application:
    # 应用的名称，不写默认为项目名
    name: take_out_food
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  redis:
    host: 192.168.30.128 # linux虚拟机
    port: 6379
    password: 123456
    database: 0
  cache:
    redis:
      time-to-live: 3600000 #以毫秒为单位，实际为3600秒
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  #上传的图片保存的位置
  path: D:\JAVA_PROJECT\TakeOut_Food\img\
#  path: /usr/local/app/imgs
